# Generated by Django 4.0.6 on 2022-07-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_company_stockinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='volume',
            field=models.PositiveIntegerField(verbose_name='成交量'),
        ),
    ]
